services:

  db:
    image: dementievnet/mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/db:/var/lib/mysql
      - ./app/log/mysql:/var/log/mysql/
      - ./config/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "0.0.0.0:3306:3306"
    networks:
      - bitrix

  phpmyadmin:
    image: dementievnet/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql5.7
    networks:
      - bitrix

  web:
    image: dementievnet/nginx:latest
    container_name: nginx
    working_dir: /etc/nginx
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./app/log/nginx:/var/log/nginx/
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    depends_on:
      - php
    networks:
      - bitrix
    links:
      - php

  php:
    image: dementievnet/php:latest
    container_name: php
    working_dir: /app/www
    volumes:
      - ./app:/app
      - ./config/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    restart: always
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    networks:
      - bitrix

networks:
  bitrix:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24