services:

  db:
    image: dementievnet/mysql:v8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./config/mysql/my.cnf:/etc/mysql/mysql.conf.d/my.cnf
      - ./app/db:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    networks:
      - bitrix

  phpmyadmin:
    image: dementievnet/phpmyadmin:v5.2.0
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: localhost
    networks:
      - bitrix

  web:
    image: dementievnet/nginx:v1.23.0
    container_name: nginx
    working_dir: /etc/nginx
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./app/log/nginx:/var/log/nginx/
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    depends_on:
      - php
    networks:
      - bitrix
    links:
      - php

  php:
    image: dementievnet/php:v7.4
    container_name: php
    working_dir: /app/www
    volumes:
      - ./app:/app
      - ./config/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    restart: always
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    networks:
      - bitrix

networks:
  bitrix:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24