services:

  mysql5.7:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/db:/var/lib/mysql
      - ./app/log/mysql:/var/log/mysql/
      - ./config/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "0.0.0.0:3306:3306"
    networks:
      - bitrix

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql5.7
    networks:
      - bitrix

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /etc/nginx
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./app/log/nginx:/var/log/nginx/
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    depends_on:
      - php
    networks:
      - bitrix
    links:
      - php

  #  php:
  #    build:
  #      context: ./config/php7.3
  #      dockerfile: Dockerfile
  #    container_name: php
  #    working_dir: /app
  #    volumes:
  #      - ./app:/app
  #      - ./config/php7.3/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
  #      - ./bin/sendmail:/usr/local/bin/sendmail
  #    environment:
  #        PHP_IDE_CONFIG: serverName=localhost

  php:
    build:
      context: ./config/php7.4
      dockerfile: Dockerfile
    container_name: php
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php7.4/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    networks:
      - bitrix

#  php:
#    build:
#      context: ./config/php8.0
#      dockerfile: Dockerfile
#    container_name: php
#    working_dir: /app
#    volumes:
#      - ./app:/app
#      - ./config/php8.0/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
#      - ./bin/sendmail:/usr/local/bin/sendmail
#    environment:
#        PHP_IDE_CONFIG: serverName=localhost

networks:
  bitrix:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24